### ISSUE TITLE
Update plugin for OJS 3.x compatibility

### ISSUE THREAD

**Issue by mfelczak** [asmecher/subscriptionSSO#1]
Hi @asmecher, adding a placeholder here; some of our existing clients are using this plugin.

**Comment by asmecher** [comment]
Branched into...
- https://github.com/asmecher/subscriptionSSO/tree/ojs2 for OJS2
- https://github.com/asmecher/subscriptionSSO/tree/master for OJS3

Created a draft release (https://github.com/asmecher/subscriptionSSO/releases/tag/1_0_1-0) for OJS 3.x. Will remove draft tag after getting feedback.

**Comment by mfelczak** [comment]
Hi @asmecher, thanks again for the plugin update. Confirming that all works as expected with a client journal running OJS 3.1.0

**Comment by asmecher** [comment]
Great, thanks -- I'll add this to the plugin gallery.
