### ISSUE TITLE
option for a dynamic login/logout button depending on SSO status

### ISSUE THREAD

**Issue by sarangtc** [asmecher/subscriptionSSO#14]
Is there a way to have a dynamic login or logout button depending on whether the user is signed in to SSO (in my case a WordPress site)

of course the login button would link to the SSO login page, and not OJS's login page.

**Comment by asmecher** [comment]
@sarangtc, not as it's currently coded. If you want to code a proper SSO, I'd suggest working with OpenID or Shibboleth; this is a very simple work-around for systems that don't support a full SSO setup.
